export const INVENTORY_ITEMS = {
    longsword: {
        id: 1231495831,
        entityTypeId: 1439493548,
        equipped: true,
        quantity: 1,
        isAttuned: true,
        definition: {
            id: 4,
            baseTypeId: 1782728300,
            entityTypeId: 1782728300,
            definitionKey: '1782728300:4',
            canEquip: true,
            magic: false,
            name: 'Longsword',
            snippet: null,
            weight: 3,
            weightMultiplier: 1,
            capacity: null,
            capacityWeight: 0,
            type: 'Longsword',
            description:
                '<p>Proficiency with a longsword allows you to add your proficiency bonus to the attack roll for any attack you make with it.</p>',
            canAttune: false,
            attunementDescription: null,
            rarity: 'Common',
            isHomebrew: false,
            version: null,
            sourceId: null,
            sourcePageNumber: null,
            stackable: false,
            bundleSize: 1,
            avatarUrl: null,
            largeAvatarUrl: null,
            filterType: 'Weapon',
            cost: 15,
            isPack: false,
            tags: ['Damage', 'Combat'],
            grantedModifiers: [],
            subType: null,
            isConsumable: false,
            weaponBehaviors: [],
            baseItemId: 4,
            baseArmorName: null,
            strengthRequirement: null,
            armorClass: null,
            stealthCheck: null,
            damage: {
                diceCount: 1,
                diceValue: 8,
                diceMultiplier: null,
                fixedValue: null,
                diceString: '1d8',
            },
            damageType: 'Slashing',
            fixedDamage: null,
            properties: [
                {
                    id: 12,
                    name: 'Versatile',
                    description:
                        'This weapon can be used with one or two hands. A damage value in parentheses appears with the property--the damage when the weapon is used with two hands to make a melee attack.\r\n\r\n',
                    notes: '1d10',
                },
            ],
            attackType: 1,
            categoryId: 2,
            range: 5,
            longRange: 5,
            isMonkWeapon: false,
            levelInfusionGranted: null,
            sources: [
                {
                    sourceId: 1,
                    pageNumber: null,
                    sourceType: 2,
                },
                {
                    sourceId: 2,
                    pageNumber: null,
                    sourceType: 1,
                },
            ],
            armorTypeId: null,
            gearTypeId: null,
            groupedId: null,
            canBeAddedToInventory: true,
            isContainer: false,
            isCustomItem: false,
        },
    },
};
